# Generated by Django 5.0.9 on 2024-10-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="Days",
            field=models.CharField(default="none", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="Hours",
            field=models.CharField(default="none", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="Ta_Classes",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
