# Generated by Django 5.0.9 on 2024-10-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_days_customuser_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="Bio",
            field=models.CharField(
                default="Hello I am a computer science grad student. I am very knowlegable on many programming languages. Lets have a great semester",
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
